### ISSUE TITLE
Transcrição automática

### ISSUE THREAD

**Issue by rafaelvalle** [renoirfaria/hardpath#15]
Vocês pensam em utilizar aprendizagem de máquinas para fazer transcrição automática do texto? Eu posso ajudar...

**Comment by DiegoCatalano** [comment]
Também posso ajudar

**Comment by ronaldmiranda** [comment]
Também posso contribuir !

**Comment by delblues** [comment]
gostaria de contribuir tmb

**Comment by renoirtech** [comment]
@all Pessoal, basta discutir os meios para que isso seja feito, tendo uma decisão basta abrir um branch e mandar bala. Toda ajuda é bem vinda!

**Comment by m4dw0lf** [comment]
Manda bala galera!

**Comment by rafaelvalle** [comment]
@renoirfaria @m4dw0lf @DiegoCatalano há um endereço web onde a versão digital, i.e imagem, das páginas do livro e das letras do alfabeto inventado? Esses items são o mínimo necessário pra fazer implementar um modelo não supervisionado.

**Comment by rafaelvalle** [comment]
Beleza. Achei os caracteres e três páginas na repo de vcs.

**Comment by rafaelvalle** [comment]
Pra quem quiser ajudar, comecei com segmentação de linha e caracteres.
https://github.com/rafaelvalle/hardpath/blob/master/line_and_character_segmentation.ipynb

**Comment by DiegoCatalano** [comment]
@rafaelvalle, Fiz uma abordagem aki, ja identifico ao menos o numero de linhas, alinho a pagina tb e ja está segmentado carácter por carácter, tem umas grandes que ainda vo identificar e corrigir, mas ja consigo salvar tudo no formato compativel estilo mnist.

![image](https://cloud.githubusercontent.com/assets/5301914/24779639/0ef66d2c-1b08-11e7-93b5-10952b6a59e6.png)

Vo implementar um image data generator para o dataset, com isso acredito que já possivel rodar uma convnet treinada do mnist e testar.

**Comment by rafaelvalle** [comment]
@DiegoCatalano 
Diego, tenta fazer template matching entre os segmentos e o alfabeto gerado com a true type font.

```python
import numpy as np
from skimage.transform import resize
from PIL import Image, ImageFont, ImageDraw, ImageOps

def get_bounding_box(image, threshold=1):
    mask = image < threshold
    if False not in mask:
        return image
    coords = np.array(np.nonzero(~mask))
    top_left = np.min(coords, axis=1)
    bottom_right = np.max(coords, axis=1)
    return image[top_left[0]:bottom_right[0], top_left[1]:bottom_right[1]]

# create 25x25 patches representing each letter in the alphabet
alphabet = 'abcdefghijlmnopqrstuvxz'
letters = []
patch_size = (25, 25)
for letter in alphabet:
    im = Image.new("RGB", patch_size)
    draw = ImageDraw.Draw(im)
    font = ImageFont.truetype("fonts/giordano/giordano-webfont.ttf", 24)
    draw.text((8, 4), letter, font=font)
    data = np.array(im.convert('L'))
    data = get_bounding_box(data)
    data = resize(data, patch_size)
    letters.append(data)
letters = np.array(letters, dtype=np.float32)

### segments é uma array com os segmentos que vc encontrou
mse = lambda x, y : np.mean((x-y)**2)
transcription = []
for segment in segments:
    best_match = np.argmin([mse(resize(segment, patch_size), letter) for letter in letters])
    transcription.append(alphabet[best_match])

```

Com image data generator você quer dizer gerar um training data a partir dos caracteres gerados com a ttf ou usar as transcrições disponíveis com esses segmentos?
A tipografia é tão regular que talvez um template matching resolva. Roda aí e avisa aqui!

**Comment by rafaelvalle** [comment]
@DiegoCatalano o ideal seria trabalharmos na mesma repo pra agilizar. 
Vamos criar uma repo exclusiva pra abordagem utilizando machine learning?

**Comment by rafaelvalle** [comment]
Abordagem *standard* para character segmentation
http://stackoverflow.com/questions/10964226/how-to-convert-an-image-into-character-segments

**Comment by DiegoCatalano** [comment]
@rafaelvalle Boa pergunta, acho que seria interessante sim, mas primeiro vamos focar na segmentação para podermos gerar um bom dataset. Vo te enviar um email com meu contato para agilizarmos.

**Comment by DiegoCatalano** [comment]
Sobre gerar o dataset estou pensando em algo desse tipo aki:
https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html

**Comment by rafaelvalle** [comment]
@DiegoCatalano podemos gerar um dataset para treinar uma CNN independente da segmentação. Nós podemos gerar templates, como no meu [comentário acima](https://github.com/renoirfaria/hardpath/issues/15#issuecomment-292369239) e usar data augmentation do [keras](url) ou d'uma library , e.g. https://github.com/aleju/imgaug.

Acho melhor irmos de keras mesmo porque podemos usar o código no link que vc postou!
Vou adaptando o código do blog por aqui!

**Comment by rafaelvalle** [comment]
@DiegoCatalano 
Aí o código pra treinar a CNN usando data augmentation em imagens de caracteres gerados a partir da fonte true type.
https://github.com/rafaelvalle/hardpath/blob/master/cnn_ocr.py

**Comment by DiegoCatalano** [comment]
Então só teremos que focar na segmentação, vo comitar a minha abordagem ja ja. Acho que rola setar o horizontal_flip=False;

Tenso vai ser os caracteres 'S' e 'B'

**Comment by rafaelvalle** [comment]
@DiegoCatalano vai comitar aonde? 
Concordo com vc em setar o horizontal_flip=False!

**Comment by DiegoCatalano** [comment]
Eu dei um fork, vo comitar no meu e envio o link aki, acho que rola separarmos em 3 tarefas independentes, segmentação, dataset e ml. O que acha ?

**Comment by DiegoCatalano** [comment]
Estou querendo organizar no seguinte aspecto:

ocr\segmentation\java\approachX
ocr\segmentation\python\approachY
...
ocr\ml\python\cnn

Até porque estou fazendo em Java, assim mais gente com diferentes linguagens podem contribuir tranquilamente, gerando o dataset dai é so pegar firme no ml.

**Comment by rafaelvalle** [comment]
Quando vc comitar eu testo classifiers com template matching e CNN

Vamos firmar na estrutura ocr/linguagem/(**segmentation**, **dataset_generation**, **transcription**)?
Não chamaria **ml** porque tudo o que estamos fazendo é ml...

**Comment by DiegoCatalano** [comment]
Beleza, vamos firmar essa estrutura então. Amanha eu ja comito e explico a abordagem adotada passo a passo.
