### ISSUE TITLE
Fonte

### ISSUE THREAD

**Issue by ghost** [renoirfaria/hardpath#21]
Criei uma fonte.
Acredito que ficará melhor do que trabalhar com imagens.
Posso aprimorar ela.

Vantagem de ser utilizável tanto online (php) quando to word.

**Comment by renoirtech** [comment]
Cara o pessoal já inseriu uma fonte e um novo teclado, dá uma testada. Se você acha que pode melhorar sinta-se em casa e manda o pull-request. Muito obrigado pelo intuito de ajudar!

**Comment by sofialunkes** [comment]
@renoirfaria a fonte está muito pequena no novo teclado, ficou um pouco mais complicado ver as letras no teclado. Encontra-se duplicado tb.

**Comment by Milleo** [comment]
@sofialunkes Vou aumentar a fonte, hoje a noite já atualizo, realmente ficou bem pequena

@fabiofurious Seria uma boa melhorar, porque essa fonte foi feita as pressas, fica a vontade pra melhorar, cara

**Comment by m4dw0lf** [comment]
Pessoal,

Obrigado pelas contribuições com as fontes. Teriam como ir fazendo de acordo com as decrypt que forem saindo ? 

Abraços!

**Comment by ghost** [comment]
Essa outra fonte ficou muito boa mesmo.

**Comment by m4dw0lf** [comment]
Show!
