### ISSUE TITLE
Como Ajudar

### ISSUE THREAD

**Issue by enieber** [renoirfaria/hardpath#23]
Poderia melhorar o Readme do projeto fazendo um mini tutorial de como traduzir e ai da para implementar onde vai ficar salvo as imagens e os texto.

**Comment by m4dw0lf** [comment]
Boa ideia,

Teria como mandar um pull request com essas mudanças ? Ajudaria bastante

**Comment by enieber** [comment]
não seria melhor deixar a issue aberta até ser resolvido e ai fecha depois?
