### ISSUE TITLE
Teclado novo

### ISSUE THREAD

**Issue by aguiarmat** [renoirfaria/hardpath#24]
ficou muito melhor, porém está saindo duplicado

**Comment by renoirtech** [comment]
@Milleo pode nos ajudar com isso, abri o código aqui porém sem sucesso.

**Comment by Milleo** [comment]
@renoirfaria  Ok, vou verificar o quanto antes, mas acho que deve ter mais de um click dando bind no teclado. Tem o do próprio plugin, mas deve ter um a mais.

**Comment by macarena** [comment]
Não é clique duplo... é que elemento button tem o span dentro dele com a segunda fonte. assim o seletor .text() do jquery pega o texto do button + span, duplicando a letra.

**Comment by lucianotonet** [comment]
Ficou bem melhor, mas além de duplicar, ele está inserindo o caractere no final do texto e não na posição do cursor, e isto eu já tinha corrigido no PR #17

**Comment by caiobleggi** [comment]
Olá, fiz uma sugestão de melhoria no teclado antigo e mudanças no visual do mesmo #30 . É possível utilizar as imagens que vocês aplicaram agora no teclado antigo também. Talvez a biblioteca dele seja mais limpa.. Não acham?
Abs

**Comment by m4dw0lf** [comment]
Teclado está modificado galera, quem quiser fazer melhoria só abrir um pull request
