### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by samverneck** [renoirfaria/hardpath#3]
Vou tentar melhorar o layout @renoirfaria

**Comment by renoirtech** [comment]
Show de bola Samuel, vamos que vamos. Muito obrigado.
Em ter, 4 de abr de 2017 às 18:13, SAMUEL VERNECK <notifications@github.com>
escreveu:

**Comment by samverneck** [comment]
achei essa img 
![imagem4](https://cloud.githubusercontent.com/assets/22237899/24679002/325a8920-1963-11e7-9085-f40cbdb85002.jpg)

**Comment by gfnord** [comment]
As três páginas já estão traduzidas?

**Comment by renoirtech** [comment]
Não, liberamos para tradução.
Em ter, 4 de abr de 2017 às 18:35, Gustavo F Nobrega <
notifications@github.com> escreveu:

**Comment by samverneck** [comment]
@renoirfaria vou só dar uma melhorada no layout, ok?

**Comment by renoirtech** [comment]
Claro, manda bala
Em ter, 4 de abr de 2017 às 21:55, SAMUEL VERNECK <notifications@github.com>
escreveu:

**Comment by samverneck** [comment]
vou ver se ainda hoje subo @renoirfaria

**Comment by renoirtech** [comment]
Massa, vamos!

**Comment by samverneck** [comment]
@renoirfaria pra onde está indo os txt já descifrados?

**Comment by renoirtech** [comment]
Por enquanto estão ficando no navegador do user, não sabíamos que ia ter
essa repercussão.
Em ter, 4 de abr de 2017 às 22:00, SAMUEL VERNECK <notifications@github.com>
escreveu:

**Comment by samverneck** [comment]
Bookmark? @renoirfaria

**Comment by renoirtech** [comment]
Através de session storage.

**Comment by samverneck** [comment]
@renoirfaria vamos abrir uma issue para avisar quando forem feitas mudanças, só vi agora que já teve mudança ;) haha

**Comment by m4dw0lf** [comment]
Modificado!
