### ISSUE TITLE
LIVRO PARA AJUDAR

### ISSUE THREAD

**Issue by samverneck** [renoirfaria/hardpath#4]
![lostsymbol](https://cloud.githubusercontent.com/assets/22237899/24679490/9cf55b2a-1963-11e7-8f5f-d490d927fcae.jpg)

Vale dar uma olhada nesse livro.
@renoirfaria

**Comment by ifalldev** [comment]
@samverneck, desculpe eu nao li a obra, infelizmente. Poderia me explicar a ligacao? Obrigado!

**Comment by samverneck** [comment]
@ifalldev Esse livro é rico em simbologias e quem sabe ele possa ter lido essa obra para se inspirar também nessas simbologias e textos cifrados usados

**Aqui esta uma visão geral do livro**

Depois de ter sobrevivido a uma explosão no Vaticano e a uma caçada humana em Paris, Robert Langdon está de volta com seus profundos conhecimentos de simbologia e sua brilhante habilidade para solucionar problemas. 
Em O símbolo perdido, o célebre professor de Harvard é convidado às pressas por seu amigo e mentor Peter Solomon - eminente maçom e filantropo - a dar uma palestra no Capitólio dos Estados Unidos. Ao chegar lá, descobre que caiu numa armadilha. Não há palestra nenhuma, Solomon está desaparecido e, ao que tudo indica, correndo grande perigo. 
Mal'akh, o sequestrador, acredita que os fundadores de Washington, a maioria deles mestres maçons, esconderam na cidade um tesouro capaz de dar poderes sobre-humanos a quem o encontrasse. E está convencido de que Langdon é a única pessoa que pode localizá-lo.
Vendo que essa é sua única chance de salvar Solomon, o simbologista se lança numa corrida alucinada pelos principais pontos da capital americana: o Capitólio, a Biblioteca do Congresso, a Catedral Nacional e o Centro de Apoio dos Museus Smithsonian.
Neste labirinto de verdades ocultas, códigos maçônicos e símbolos escondidos, Langdon conta com a ajuda de Katherine, irmã de Peter e renomada cientista que investiga o poder que a mente humana tem de influenciar o mundo físico. 
O tempo está contra eles. E muitas outras pessoas parecem envolvidas nesta trama que ameaça a segurança nacional, entre elas Inoue Sato, autoridade máxima do Escritório de Segurança da CIA, e Warren Bellamy, responsável pela administração do Capitólio. Como Langdon já aprendeu em suas outras aventuras, quando se trata de segredos e poder, nunca se pode dizer ao certo de que lado cada um está.
Nas mãos de Dan Brown, Washington se revela tão fascinante quanto o Vaticano ou Paris. Em O Símbolo Perdido, ele desperta o interesse dos leitores por temas tão variados como ciência noética, teoria das supercordas e grandes obras de arte, os desafiando a abrir a mente para novos conhecimentos
**FONTE:** http://www.saraiva.com.br/o-simbolo-perdido-2688621.html

**Comment by m4dw0lf** [comment]
Massa!
