### ISSUE TITLE
Ideia de projeto

### ISSUE THREAD

**Issue by daviaws** [renoirfaria/hardpath#5]
Há seis meses atrás, tive uma ideia com um amigo de começar um projeto de identificação de texto em imagens e tradução.
A ideia era poder ler textos escritos em outras línguas.

A aplicação seria mais abrangente, como um óculos que lê, traduz(ou não) e te devolve em audio. (Ajudaria cegos e pessoas querendo ler textos em línguas desconhecidas).

Teria ótima aplicação nesse caso também, e pouparia o tempo de muita gente traduzindo manualmente.

**Comment by renoirtech** [comment]
Cara o que precisa para aplicar isso aqui?
Em ter, 4 de abr de 2017 às 18:52, daviaws <notifications@github.com>
escreveu:

**Comment by daviaws** [comment]
Desenvolver. A ideia já surgiu. Tecnologia para isso já existe. Amanhã tenho uma reunião com uma professora sobre esse trabalho.
Mas ta aí, achei que valia a pena partilhar a sugestão.

**Comment by renoirtech** [comment]
Beleza vamos estudar a viabilidade.

**Comment by enieber** [comment]
o que da pra fazer é usar aprendizado de maquina para fazer a leitura as imagens e transformar em text para poder ser traduzido manual ou altomaticamente

**Comment by m4dw0lf** [comment]
Show! Parece que tem um pessoal já  desenvolvendo isso.
