### ISSUE TITLE
back-end

### ISSUE THREAD

**Issue by flaviolpgjr** [renoirfaria/hardpath#53]
E ai galera, trabalho com python/django, se quiserem posso contribuir com essa parte

**Comment by flaviolpgjr** [comment]
posso tentar fazer uma api rest, pra tentarem acessar via ajax

**Comment by Milleo** [comment]
É um ponto importante @flaviolpgjr , precisamos de um planejamento de como seria o sistema. E você faria o Back-end em que linguagem?

**Comment by flaviolpgjr** [comment]
então, pensei em fazer uma rest em python/django do o Django rest framework, no qual acessariam via get/post

**Comment by xxdf** [comment]
olá @flaviolpgjr eu também trabalho com python/django estou acompanhando o hardpath desde ontem, mas não encontrei algo em que eu pudesse ser útil ainda, sei muito pouco até mesmo sobre o github, mas se algo estiver no meu alcance, vou procurar ajudar também.

**Comment by Milleo** [comment]
@m4dw0lf @renoirfaria Senhores, o servidor de hospedagem tem qual configuração? Podemos usar qualquer linguagem?

**Comment by flaviolpgjr** [comment]
@xxdf @Milleo , a ajuda de vcs será bem vinda, então, se fizermos a api, podemos hospedar ela em um servidor a parte, e no caso, o front só consumiria essa API

**Comment by renoirtech** [comment]
@Milleo, no momento utilizamos o servidor básico da Umbler.com.br que está surpreendentemente aguentando a pancada de mais de 100k de acessos.

Se bem que é apenas um front-end dai nem cobra muito do server.

Esse server mais barato só suporta PHP e .NET, eu sugiro a utilização de PHP até porque estou fazendo uma parceria com a comunidade de PHP para que mais pessoas de back-end possam vir nos ajudar e também porque é a linguagem que eu trabalho.

Quem sabe um laravel para agilizar o processo??

**Comment by flaviolpgjr** [comment]
se animarem fazer api em python eu me disponibilizo, agora PHP sei nada!!

**Comment by samverneck** [comment]
Para o BD vão usar o que?
Sugestão MongoDB e NodeJS

**Comment by Milleo** [comment]
Eu trabalho com php, já tenho bastante experiência, alguém mais tá afim de fazer? Mesmo quem não sabe nada, já é bom pra começar

**Comment by Milleo** [comment]
Eu estou aprendendo Laravel, seria muito bom pra todo mundo aprender também, mas se for último caso poderíamos usar um codeigniter, não?

**Comment by iagocavalcante** [comment]
Sei laravel e codeigniter, o que vai ser preciso no backend ?

**Comment by samverneck** [comment]
Não sei quase nada de back é como vc falou é um começo @Milleo rsrs

**Comment by Milleo** [comment]
@samverneck aí sim! É uma boa oportunidade pra já começar a aprender e ver como funciona!

@renoirfaria acho que seria uma boa abrir uma nova issue (ou até mesmo um projeto dependente) pra começarmos o planejamento do back-end, o que acha? O conceito ainda não foi apresentado, mas estou imaginando um sistema onde todos podem traduzir os textos e submeter os rascunhos para revisão da própria comunidade.

**Comment by samverneck** [comment]
@Milleo @renoirfaria ou até msm uma organização aqui no github, que dai podemos expandir mais e virarmos pesquisadores dessas paradas como já estamos fazendo, o que acha?

**Comment by Takaharayuri122** [comment]
Galera vocês já pensaram em fazer algo como Visual Reconition para ajudar nas traduções?

**Comment by lucianotonet** [comment]
Gente, eu trabalho com Laravel. Seria barbaba pra mim levantar uma API com banco de dados e autenticação de usuários, porém, deveríamos ter tudo bem planejado, pois estou curto de tempo.

Ainda não compreendi direito o objetivo deste projeto, visto que estamos todos traduzindo o mesmo material que outros ja traduziram, e não consigo pensar em como poderíamos fazer isto de forma colaborativa, sem retrabalho. Já rolou alguma ideia q não peguei?

Tudo que temos são materiais aleatórios. E quando liberarem o conteúdo dos livros? Como vai ser?

@renoirfaria e Igor Rincon estão aparecendo em vários sites. Podemos enviar nossas fotos pra aparecer também? XD

**Comment by renoirtech** [comment]
Grande Luciano, vamos fazer em Laravel, eu posso ajudar muito também.

Podemos fazer uma sessão de contribuintes para que nas entrevistas eu
mostre.
Em qui, 6 de abr de 2017 às 16:50, Luciano Tonet <notifications@github.com>
escreveu:

**Comment by igorquintaes** [comment]
Eu tenho conhecimento em .NET com C#. Caso decidam partir para programar o back com essa linguagem, também posso ajudar

**Comment by walteribeiro** [comment]
Boa noite, trabalho com PHP também inclusive o Laravel, se quiserem posso contribuir com uma API também.

**Comment by enieber** [comment]
@renoirfaria tem uma opção do proprio github para gerenciar projetos, podemos usar ela para desenvolver e melhorar as coisas por de traz dos panos e deixar as issues para traduzir como eu sugerir na pr #58

**Comment by kistaaa** [comment]
Eu trabalho com javascript, se vocês quiserem recomendo o firebase: rápido, tem https, banco de dados parecido com mongodb (json), hosting, storage, e uma opção free até um certo limite de tráfego: https://firebase.google.com/
Pode também ser usando como api em android, C, e outras linguagens.
To achando ótimo até agora, qualquer coisa da um toque!

**Comment by renoirtech** [comment]
Vou fazer algo aqui em relação a isso hoje

**Comment by samverneck** [comment]
show! @renoirfaria

**Comment by samverneck** [comment]
vai ser com laravel msm?

**Comment by snakeice** [comment]
Se for go, java ou php posso ajudar tmb

**Comment by snakeice** [comment]
Poderíamos também montar um esquema de locação de trecho, ai o vivente entra, loca pra ele o trecho a ser traduzido ai não haveria  conflito de tradução, dai pra frente só melhorias na base traduzida, dividimos as imagens em partes menores para otimizar o processo e poder obter ter mais colaboradores no processo..

**Comment by snakeice** [comment]
Ah...Mais uma coisa, uahahua.. Adiciona os programadores no projeto ai usamos a aba projects para dividir as tarefas e gerenciar a evolução e as issues referentes a melhorias e correções...

**Comment by m4dw0lf** [comment]
Fala @Snakeice tu tem vontade de nos ajudar a organizar o projeto ? Porque estamos bastante corrridos aqui e estamos um pouco sem tempo. Se quiser podemos ver para te dar alguma permissão

**Comment by snakeice** [comment]
Vontade tenho, não tenho muito tempo, mas ajudo sim!

**Comment by OwlRC** [comment]
Posso colaborar com tradução e organização dos arquivos.

**Comment by samverneck** [comment]
como ficou as paradas?
