### ISSUE TITLE
Libera a WIKI

### ISSUE THREAD

**Issue by kelvinrfr** [renoirfaria/hardpath#56]
@renoirfaria 
Opa, libera a Wiki em um formato onde terá a Imagem e a tradução em seguida. Vai ser muito mais facil de consultar e entender mais sobre o assunto. 
Usáriamos o teclado criado aqui pra atualizar a wiki.
Dá joinha aqui quem concorda.

**Comment by renoirtech** [comment]
Bacana, libero sim
Em qui, 6 de abr de 2017 às 14:42, Kelvin Ferreira <notifications@github.com>
escreveu:

**Comment by renoirtech** [comment]
Acabei de habilitar! Vamos que vamos!

**Comment by kelvinrfr** [comment]
Boa! Eu criei lá... Será que tem como você apagar a pagina Home e deixar ir
direto pra sumário que criei lá?
Da uma olhada la tbm da estrutura q tava pensando

Kelvin Rodrigues Ferreira
blog: http://kelvinrodrigues.wordpress.com

2017-04-06 15:01 GMT-03:00 Renoir dos Reis <notifications@github.com>:
