### ISSUE TITLE
Trello com material organizado

### ISSUE THREAD

**Issue by lucianotonet** [renoirfaria/hardpath#60]
Encontrei isso:
Trello: https://trello.com/b/YKCHM0hD/giordano-bruno-borges

Não seria interessante nos unirmos com esse pessoal de alguma forma? Já q o assunto é o mesmo...

Vi também que existem dois grupos no Facebook e no WhatsApp:
Bruno Borges - Estudos: https://www.facebook.com/groups/263107910816676/
Bruno Borges - As Teorias: https://www.facebook.com/groups/1905488029722555/

Grupos dos whats não tenho os links.

**Comment by m4dw0lf** [comment]
@Milleo Poderia subir as imagens desse trello para o site ? Adicionamos o novo layout que você enviou

**Comment by m4dw0lf** [comment]
@renoirfaria se puder ajudar também

**Comment by Milleo** [comment]
Ok, vou fazer assim que puder (a noite)

**Comment by Milleo** [comment]
Feito no PR #64

**Comment by beavisualartist** [comment]
galera, o trello é meu, é soh me mandar o email q  eu adiciono no painel pra ser editor tambem.

**Comment by beavisualartist** [comment]
achei q la fica bem organizado e a galera ta somando coletivamente tbm. é uma ferramenta bem pratica

**Comment by DrellDeveloper** [comment]
me coloca no trello: drelldeveloper@gmail.com
