### ISSUE TITLE
Não seria o próprio Bruno?

### ISSUE THREAD

**Issue by lucianotonet** [renoirfaria/hardpath#69]
Alguém comentou à pouco num grupo de zoeira do Face que o Bruno estaria acompanhando tudo dos bastidores. Fui pesquisar e... será?

Olhem as fotos desse perfil... indicam ser um perfil dele
https://www.facebook.com/profile.php?id=100015145806604&lst=100000236776954%3A100015145806604%3A1491626899&sk=photos
![image](https://cloud.githubusercontent.com/assets/2693019/24825868/d24505d0-1bfe-11e7-93e7-760c088c8a7d.png)

![image](https://cloud.githubusercontent.com/assets/2693019/24825878/05b1aee6-1bff-11e7-953a-4b5c1255cabc.png)

Detalhe:
Este perfil tinha um amigo Charles Videon que tava curtindo as coisas no face de modo suspeito, e agora não tem aparece mais esse perfil 
![image](https://cloud.githubusercontent.com/assets/2693019/24825894/75f1a6e8-1bff-11e7-83b2-c70e71f885f5.png)

Ele deve estar é rindo da nossa cara...
(ou se 'moiando' de ver tanta gente doida interessada nas coisas dele)

**Comment by lucianotonet** [comment]
Perfil do próprio:
https://www.facebook.com/bruno.borges.73594

**Comment by lucianotonet** [comment]
Humm... 
Sobre o perfil do Facebook
- 290 amigos 
- Todas as fotos postadas dia 02 de fevereiro (e omitidas da linha do tempo)
- Nenhuma postagem antes dessa data

Fake?
Tem treta essa história aí.

**Comment by KalevMosher** [comment]
Hello.
não e apenas um perfil..
são vários. 
um "fake não anda só" tem que ter quem comentar e da like para sustentar.

Ou as mentes são muito iguais, ou não sei.

https://www.facebook.com/paulo.sidney.9
https://www.facebook.com/Iluminatss

https://www.facebook.com/profile.php?id=100011556547864&fref=ufi  <- pouco tempo de uso, por isso o 

numeral como "nome", ou porque não foi "validado" 
porque apenas 24 "amigos"

https://www.facebook.com/profile.php?id=100011556547864&sk=friends&pnref=lhc


os comentários com analise em bases de objetos, "maçom, hebreu, "seitas" "iluminismos" sempre deixa "dicas" de posições de objetos ou artefatos simbólicos.

Sim foi tudo feito em uma data, tudo tem um proposito..

Mais tarde eu continuo.

**Comment by ronaldmiranda** [comment]
E outra coisa intrigante é a quantidade de amigos aumentando , originalmente ele estava com 287 no dia que desapareceu , existem diversas hipóteses

**Comment by IndayaSpindola** [comment]
Ola! 
Digamos que a estatua custa 20 mil reais.
O escultor cobrou de Bruno somente 7 mil reais por que acredita nos projetos do mesmo.
Sendo assim sobram 13 mil reais ainda.
Acredito que ele deve ter pegado o restante do dinheiro e deve ter feito uma viagem,onde o mesmo quis ficar sozinho.
Pois ele deve pensar na maneira de agir quando ele aparecer por que de fato muita gente vai querer falar com ele!
Bom fico por aqui Abraço a todos!

**Comment by aliciamedeiros** [comment]
oi pessoal andei investigando a vida dele na internet, estou acompanho o forum há alguns dias mas só agora eu acho que posso falar alguma coisa. Lembrando q pode não ser nada e eu apenas estar sendo paranoica ou falando um monte de merda, então já peço desculpas, mas vamos lá
Eu li em varios lugares que ele cursa psicologia, mas eu não sabia que ele tinha cursado sociologia. Como pode ser visto nessa lista de "jubilamento" (desligamento completo ou expulsão de um aluno da faculdade, ele foi "expulso" do curso de sociologia
![screenshot_2017-04-07-22-12-02](https://cloud.githubusercontent.com/assets/27079153/24830577/3e976074-1c5f-11e7-8875-fbdf6b1a3b13.png)
agora vamos a parte do dinheiro. Pra quem leu uma das reportagens do G1, (com fontes apenas da familia o que já é suspeito em si) Fala que ele pediu dinheiro a familia pra publicar os livros porque nao o tinha, o que foi negado, mas conseguiu recentemente dinheiro com um primo. Mas em uma pesquisa com o nome dele eu achei que ele tem uma empresa resgistrada em seu nome! e foi registrada no fim do ano passado 
![screenshot_2017-04-07-22-09-05](https://cloud.githubusercontent.com/assets/27079153/24830604/00b1548a-1c60-11e7-8e31-931aa33fc07a.png)
mas dai vc vai me dizer, ah ele deve ter registrado para os pais dele ou algum parente, e de fato isso é bem comum, mas dai que eu pesquisei sobre a familia dele tambem
![screenshot_2017-04-07-22-18-18](https://cloud.githubusercontent.com/assets/27079153/24830609/226b1d68-1c60-11e7-8e35-1e99d32f8ee3.png) essa é a empresa do pai dele (ou da familia como veremos a seguir)
![screenshot_2017-04-07-22-47-34](https://cloud.githubusercontent.com/assets/27079153/24830617/3686838c-1c60-11e7-8422-e58bb3f793c1.png)
![screenshot_2017-04-07-22-47-51](https://cloud.githubusercontent.com/assets/27079153/24830618/36929e60-1c60-11e7-9d89-5e3ab20df7ce.png)
o pai dele tem 2 registradas no nome já. Basicamente eles são ricos, but ok. Pobre garoto não deram dinheiro a ele. 
mas aqui, pode se ver que  ele recebe pensão do governo ou algo assim 
![screenshot_2017-04-07-22-17-50](https://cloud.githubusercontent.com/assets/27079153/24830625/5dc4c3a0-1c60-11e7-9474-dcacd95f0f4a.png) (não estou muito certo sobre isso, não sou especialista)
voces provavelmente viram sobre esse anuncio, não consegui pescar a data que esse print que está no trello foi postado, mas ontem a noite o anuncio já não está mais disponivel. 
![screenshot_2017-04-07-22-14-36](https://cloud.githubusercontent.com/assets/27079153/24830632/6ffb2d16-1c60-11e7-8b4b-d3a24fc2544c.png)
![screenshot_2017-04-07-22-27-00](https://cloud.githubusercontent.com/assets/27079153/24830633/701c4eb0-1c60-11e7-8a65-d916ba1f7084.png)
por agora é isso que consegui reunir. Se mais alguem tiver informações que quiser agregar sobre isso ou me dizer que estou completamente errada, tudo bem. Só sou outro curioso no meio de tudo isso.

**Comment by aliciamedeiros** [comment]
E se não for um golpe publicitario pra divulgação dos livros dele, ele poderia ter realmente ligação com o cicada 3301 como diz aqui? https://www.tecmundo.com.br/criptografia/115625-jovem-sumiu-acre-deixa-imagem-enigmatica-cicada-3301.htm

**Comment by aliciamedeiros** [comment]
E se não for um golpe publicitario pra divulgação dos livros dele, ele poderia ter realmente ligação com o cicada 3301 como diz aqui? https://www.tecmundo.com.br/criptografia/115625-jovem-sumiu-acre-deixa-imagem-enigmatica-cicada-3301.htm

**Comment by lucianotonet** [comment]
Legal @aliciamedeiros . Claro que não significa nada, mas olhei no Google maps o endereço da suposta empresa dele (Rua Girassol 640, Eldorado, Acre) e... 
![image](https://cloud.githubusercontent.com/assets/2693019/24831693/1c5f2a30-1c75-11e7-85d6-c7661ddf418d.png)

https://www.google.com.br/maps/@-9.9397958,-67.7960889,3a,89.9y,75.82h,86.48t,1.69r/data=!3m6!1e1!3m4!1sRX7uXhiy14N_J8XBtHXe7w!6s%2F%2Fgeo0.ggpht.com%2Fmaps%2Fphotothumb%2Ffd%2Fv1%3Fbpb%3DChAKDnNlYXJjaC5UQUNUSUxFEkAKEgmNUQAkm4x_kRFRYt9rpeqoTBIKDXROE_oVCCOX1xoSCT9Ky6aajH-RESW-3OAmbYsFKgoNdE4T-hUII5fXGgUIahCIAw%26gl%3DBR!7i13312!8i6656!6m1!1e1?hl=pt-BR

Sim, a foto o Google é de 2012.

**Comment by IvyMB** [comment]
@tonetlds  Não da pra saber muito pelo google maps tambem, pq um dia estava pesquisando o endereço do meu amigo de RS e não aparecia a residência certo, o négocio é pesquisar em vários sites que disponibilizam mapas.

**Comment by IndayaSpindola** [comment]
https://www.facebook.com/photo.php?fbid=126300417883706&set=ecnf.100015112456102&type=3&theater

Reparem que nesta foto ele esta com algo dentro da boca

https://www.facebook.com/photo.php?fbid=126300961216985&set=ecnf.100015112456102&type=3&theater


esta aqui já não!
peço desculpas se for paranoia minha mas achei bem curioso isso

27 fotos em 3 álbuns. E ele desapareceu dia...27/03! 


Detalhe ha uma rapaz junto com ele nessas fotos 
https://www.facebook.com/photo.php?fbid=126305167883231&set=a.126279711219110.1073741829.100015112456102&type=3&theater

https://www.facebook.com/photo.php?fbid=126305194549895&set=a.126279711219110.1073741829.100015112456102&type=3&theater

https://www.facebook.com/photo.php?fbid=126301491216932&set=a.126279711219110.1073741829.100015112456102&type=3&theater


Já pararam pra pensar que ele teve ajuda de alguém pra fazer tudo isso?
Não estou dizendo que eh este rapaz mas ele parece bem intimo de Bruno 

Novamente peço  desculpas se for coisa da minha cabeça!

**Comment by lucianotonet** [comment]
@IndayaSpindola 
Sobre o rapaz q aparece nas fotos...
![image](https://cloud.githubusercontent.com/assets/2693019/24834990/10604286-1ccb-11e7-8739-f595e8fc4ea8.png)

**Comment by IndayaSpindola** [comment]
@tonetlds   
1° Imagem 
https://2.bp.blogspot.com/-FT-hpi2RAXE/WN-scdiw8TI/AAAAAAAAA3M/qedvGhyw3


2° Imagem 

https://2.bp.blogspot.com/-PhX6ssMqARk/WN-scE7f8ZI/AAAAAAAAA3I/JmGaqCScShEv2DZgrDOnoOjNibWp4r9SQCEw/s320/WHPHnOJ.jpg

3° Imagem 

https://4.bp.blogspot.com/-08MbPM-Bhko/WN-sbk1jreI/AAAAAAAAA3A/p5_9Twpwiwo8l2brdG0YCBkz6yWPRRJLwCEw/s320/eY9mlJn.jpg

4° Imagem 
https://4.bp.blogspot.com/-u9iR8G3ieTA/WN-scP-7egI/AAAAAAAAA3E/dHSzzDuRc_gsXMhzSM7FiBKe5iW2ls4uwCEw/s1600/dDeP9AD.jpg


Bom não sei se serve pra alguma coisa,mas andei pesquisando mais sobre o Bruno e achei isso não sei se eh verdade,não conheço essa pessoa.
Estou aqui em cabulada igual a todos vcs!
Também quero saber o que aconteceu com ele e sim eu acredito nos projetos dele!
Bom espero que possamos decifrar tudo isso! 
abraços
