### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Suburbanno** [renoirfaria/hardpath#93]
Enfim é isso? a comunidade abandonou? até parece que já foi tudo resolvido

**Comment by renoirtech** [comment]
Olá @Suburbanno,  eu e @m4dw0lf estamos bastante ocupados com nosso trabalho principal que é a Antecipe, aparentemente os desenvolvedores da comunidade também estão bem ocupados (tendo em vista que nenhum PR foi solicitado nos ultimos tempos). Nós estamos monitorando as traduções que chegam mas infelizmente sozinhos não conseguimos manter o desenvolvimento.
